### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by Nessrine88**
For this milestone I have :

- Implemented mission joining - Actions: 
- Implemented mission leaving - Actions: 
- Implemented switching badges for mission
- Created "Mymissions file" to render the joined missions 
- Inserted "Mymissions file" into "MyProfile file"

Thanks for reviewing.

### CODE REVIEW

**Review by ZabihullahNooriWardak — CHANGES_REQUESTED** [review]
HI  @Nessrine88  
Great job on implementing the project requirements.
you have done a great job working on this part of the project.
but there are some issues to be addressed :


1. _when we join a mission and then leave to profile page the join mission state is going to be lost_ 

I hope to implement the above changes.
happy coding.

**Comment by jlberbesi** [comment]
@Nessrine88 Hey Ness. Everything is running fine at my end.  

So  I  can say:

Merge it, Merget it, Merge it!!  🚀

**Review by jlberbesi — APPROVED** [review]
Great! you made it

**Comment by Nessrine88** [comment]
@jlberbesi  Thanks 😃

**Pull request merged**
